"""Finalizing MVP models

Revision ID: 1cb54f09dd86
Revises: 
Create Date: 2025-12-08 19:00:09.986621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1cb54f09dd86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - START ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('listings',
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('price_per_night', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('profiles',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('picture_url', sa.String(length=255), nullable=True),
    sa.Column('preferences', sa.Text(), nullable=True),
    sa.Column('demographic_info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('bookings',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('traveller_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.listing_id'], ),
    sa.ForeignKeyConstraint(['traveller_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('listing_tags',
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.listing_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ),
    sa.PrimaryKeyConstraint('listing_id', 'tag_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.listing_id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('traveller_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.listing_id'], ),
    sa.ForeignKeyConstraint(['traveller_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('invoices',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    
    # --- DEEL DAT DE AFHANKELIJKHEDEN OPLOST ---

    with op.batch_alter_table('activity_type', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('country',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('interest_categ',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
        batch_op.drop_constraint('activity_type_supplier_id_fkey', type_='foreignkey') # Moet hier worden verwijderd
        batch_op.drop_column('URL_image')
        batch_op.drop_column('supplier_id')

    with op.batch_alter_table('itinerary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('day_activity_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.alter_column('traveler_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        
        # Verwijder de oude Foreign Keys van Itinerary
        batch_op.drop_constraint('itinerary_agency_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('itinerary_traveler_id_fkey', type_='foreignkey')
        
        # Voeg de nieuwe, correcte Foreign Keys toe
        batch_op.create_foreign_key('fk_itinerary_traveler', 'traveler', ['traveler_id'], ['traveler_id'])
        batch_op.create_foreign_key('fk_itinerary_activity', 'activity_type', ['day_activity_id'], ['activity_type_id'])
        
        batch_op.drop_column('start_date')
        batch_op.drop_column('agency_id')
        batch_op.drop_column('country')
        batch_op.drop_column('number_of_travelers')
        batch_op.drop_column('end_date')
        batch_op.drop_column('activity_type')
        batch_op.drop_column('name')

    with op.batch_alter_table('traveler', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('budget_range', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('accommodation_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('adults', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('children', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('interest_culture', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('interest_food', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('interest_wildlife', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('interest_history', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('interest_beach', sa.Integer(), nullable=True))
        batch_op.drop_constraint('traveler_email_key', type_='unique') # Gebruik de string naam van de constraint
        batch_op.drop_column('password')
        batch_op.drop_column('dob')
        batch_op.drop_column('surname')
        batch_op.drop_column('gender')
        batch_op.drop_column('name')
        batch_op.drop_column('email')

    # --- DEEL DAT DE OUDE TABELLEN VERWIJDERT (MET CASCADE) ---
    # Dit moet NA alle batch_alter_table commando's die afhankelijkheden verwijderen.
    op.drop_table('activity', drop_cascade=True)
    op.drop_table('agency', drop_cascade=True)
    op.drop_table('supplier', drop_cascade=True)
    
    # --- DEEL DAT DE NIEUW ONGEWENSTE TABELLEN VERWIJDERT (GEDAAN door de creatie van nieuwe modellen) ---
    op.drop_table('invoices')
    op.drop_table('reviews')
    op.drop_table('messages')
    op.drop_table('listing_tags')
    op.drop_table('bookings')
    op.drop_table('profiles')
    op.drop_table('notifications')
    op.drop_table('listings')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('categories')

    # ### commands auto generated by Alembic - END ###


def downgrade():
    # De downgrade functie moet ALLEEN de commands bevatten die nodig zijn om de upgrade ongedaan te maken.
    # Aangezien dit een schone MVP is, is deze code minder cruciaal voor de directe werking.
    # ... (Laat de downgrade code zoals deze was als je hem niet gaat gebruiken)
    pass # Laat de downgrade functie leeg als je de reverse operatie niet hoeft te implementeren.